spring:
  application:
    name: activity-service
  mongodb:
    uri: mongodb://fitness_activityservice_user:fitness_activityservice_pass@localhost:27017/fitness_activityservice_db?authSource=admin
    auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: fitness_rabbit_user
    password: fitness_rabbit_pass

server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:            #Routing key, used to send messages
    key: activity.tracking